
// This file is automatically generated. DO NOT EDIT, all your changes would be lost.

package io.github.wangyng.flutter_sensors;

import io.flutter.plugin.common.EventChannel;

public class FlutterSensorsEventSink {
    EventChannel.EventSink event;
}
