
// This file is automatically generated. DO NOT EDIT, all your changes would be lost.

//
//  FlutterSensorsEventSink.h
//  Pods
//
//  Created by 汪洋 on 2024/8/26.
//

#import <Foundation/Foundation.h>
#import <Flutter/Flutter.h>

@interface FlutterSensorsEventSink : NSObject <FlutterStreamHandler>

@property (nonatomic, copy) FlutterEventSink event;

@end
