
// This file is automatically generated. DO NOT EDIT, all your changes would be lost.

//
//  FlutterSensorsApi.h
//  Pods
//
//  Created by 汪洋 on 2024/8/26.
//

#import <Foundation/Foundation.h>
#import <Flutter/Flutter.h>
#import "FlutterSensorsEventSink.h"

@protocol FlutterSensorsApiDelegate <NSObject>

- (void)setAccelerometerEventStream:(FlutterSensorsEventSink *)accelerometerEventStream;

- (void)register;

- (void)unregister;

@end

@interface FlutterSensorsApi : NSObject

+ (void)setup:(NSObject<FlutterPluginRegistrar> *)registrar api:(id<FlutterSensorsApiDelegate>)api;

@end

